name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  sqflite: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist_regular.ttf
        - asset: assets/fonts/urbanist_medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist_semibold.ttf
          weight: 600
        - asset: assets/fonts/urbanist_bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/worksans_medium.ttf
          weight: 500
        - asset: assets/fonts/worksans_semibold.ttf
          weight: 600
